const myData = {
    rarity: [
        "Common",
        "Uncommon",
        "Rare",
        "Rare Holo",
        "Rare Holo EX",
        "Rare Ultra",
        "Rare Holo GX",
        "Rare Holo LV.X",
        "Rare Prime",
        "Rare Holo V",
        "Rare ACE",
        "Rare BREAK",
        "Rare Prism Star",
        "Rare Holo VMAX",
        "Rare Rainbow",
        "Rare Shiny",
        "Rare Shining",
        "Amazing Rare",
        "Rare Secret",
        "Rare Shiny GX",
        "Rare Holo Star",
        "LEGEND",
        "Promo"
    ],
    subtypes: [
        "BREAK",
        "Baby",
        "Basic",
        "EX",
        "GX",
        "Goldenrod Game Corner",
        "Item",
        "LEGEND",
        "Level-Up",
        "MEGA",
        "Pokémon Tool",
        "Pokémon Tool F",
        "Rapid Strike",
        "Restored",
        "Rocket's Secret Machine",
        "Single Strike",
        "Special",
        "Stadium",
        "Stage 1",
        "Stage 2",
        "Supporter",
        "TAG TEAM",
        "Technical Machine",
        "V",
        "VMAX"
    ],
    types: [
        "Colorless",
        "Darkness",
        "Dragon",
        "Fairy",
        "Fighting",
        "Fire",
        "Grass",
        "Lightning",
        "Metal",
        "Psychic",
        "Water"
    ],
    supertypes: [
        "Energy",
        "Pokémon",
        "Trainer"
    ]
}

export default myData